@startuml
title "Isian Data Anggaran Belanja"
|Operator Desa (Administrator)|
start
:Klik Menu Isian Data
Anggaran pada Data Entri
Penganggaran;
|Aplikasi Siskeudes (System)|
:Menampilkan Menu
Isian Data Anggaran;
note right
    ..........................
end note
|Operator Desa (Administrator)|
:Pilih Desa;
:Pilih Menu **Belanja**;
|Aplikasi Siskeudes (System)|
:Mengenerate dan menampilkan
kode bidang yang telah di input
pd RKPDes awal;
|Operator Desa (Administrator)|
if (revisi?) then (yes)
    :ubah data;
    |Aplikasi Siskeudes (System)|
    :Menyimpan data;

else (no)
endif
|Operator Desa (Administrator)|
:Memilih Kode Bidang;
|Aplikasi Siskeudes (System)|
:Mengenerate dan Menampilkan
kode subbidang yang telah
di input pd RKPDes awal;
|Operator Desa (Administrator)|
if (revisi?) then (yes)
    :ubah data;
    |Aplikasi Siskeudes (System)|
    :Menyimpan data;
else (no)
endif
|Operator Desa (Administrator)|
:Memilih Kode Sub Bidang;
|Aplikasi Siskeudes (System)|
:Mengenerate dan Menampilkan
data per kode kegiatan yang
telah diinput pada RKPDes awal;
note right
    Data yang di generate:
    - Kode Kegiatan
    - Nama Kegiatan
    (generated dari kode keg)
    - Lokasi
    - Waktu (bulan)
    - Pagu (Rp)
    - Nama Pelaksana
    - Jabatan PPKD (generated
    nama pelaksana)
    - Keluaran
    - Volume Keluaran
    - Satuan Keluaran
end note
|Operator Desa (Administrator)|
if (revisi?) then (yes)
    :ubah data;
    |Aplikasi Siskeudes (System)|
    :Menyimpan data;

else (no)
endif
|Operator Desa (Administrator)|
:Memilih salah satu
kode Kegiatan;
|Aplikasi Siskeudes (System)|
:Mengenerated dan Menampilkan
Paket Kegiatan dari RKPDes awal;
note right
    Data yang di generate:
    - No ID
    - Nama Paket
    - Nilai (Rp)
    - Pola Kegiatan
    - Target Output
    - Satuan Output
    - Uraian Output
    - Sumberdana
    - Sifat Kegiatan
    - Lokasi Kegiatan
    - Tagging
    - Rencana Waktu Mulai
    - Rencana Waktu Selesai
    - Sasaran Penerima (pria, wanita)
    - Rencana Anggaran Kas (Jan-Des)
      DENGAN 4 METODE:
      - Mengisi manual per bulan
      - Bagi per termin
      - Bagi per persentase x termin
      - Bagi rata per bulan
end note
|Operator Desa (Administrator)|
if (revisi?) then (yes)
    :ubah data;
    |Aplikasi Siskeudes (System)|
    :Menyimpan data;
else (no)
endif
|Operator Desa (Administrator)|
:Memilih salah satu
Paket Kegiatan;
|Aplikasi Siskeudes (System)|
:Mengenerated dan Menampilkan
RAB dari RKPDes awal;
note right
    Data yang di generate:
    - Kode Rekening
    - Nama Rekening
    (generated by kode)
end note
|Operator Desa (Administrator)|
if (revisi?) then (yes)
    :ubah data;
    |Aplikasi Siskeudes (System)|
    :Menyimpan data;

else (no)
endif
|Operator Desa (Administrator)|
:Memilih salah satu RAB;
|Aplikasi Siskeudes (System)|
:Mengenerate dan Menampilkan
RAB Rinci dari RKPDes awal;
note right
    Data yang di generate:
    - Nomor Urut
    - Uraian
    - Kuantitas
    - Satuan
    - Harga Satuan
    - Sumberdana
end note
|Operator Desa (Administrator)|
if (revisi?) then (yes)
    :ubah data;
    |Aplikasi Siskeudes (System)|
    :Menyimpan data;

else (no)
endif
|Operator Desa (Administrator)|
stop
@enduml