@startuml
title "Rencana Anggaran Kas"
|Operator Desa (Administrator)|
start
:Klik Menu Anggaran Kas Desa
pada Data Entri Penganggaran;
|Aplikasi Siskeudes (System)|
:Menampilkan Menu
Anggaran Kas Desa;
note right
    ..........................
end note
|Operator Desa (Administrator)|
:Pilih Desa;
fork
    :**Pendapatan**;
    :Men-load/Mengupdate
    anggaran pendapatan
    per kode rekening;
    repeat
        :Memilih salah satu
        kode rekening;
        :Mengalokasikan RAK;
        note left
            Input:
            - Jan s.d. Des
            Metode:
            - Mengisi manual per bulan
            - Bagi per termin
            - Bagi per persentase x termin
            - Bagi rata per bulan
        end note
        if (simpan?) then (yes)
            :simpan data;
            |Aplikasi Siskeudes (System)|
            :Menyimpan
            input RAK;
        else (no)
            |Operator Desa (Administrator)|
            :batal;
            |Aplikasi Siskeudes (System)|
            :clear data input;
        endif
        |Operator Desa (Administrator)|
    repeat while (Data Lain?) is (yes)
    ->no;
    stop
fork again
    :**Belanja**;
    :Memilih Kode 
    Bidang dan Kegiatan;
    :Men-load/Mengupdate
    anggaran belanja
    per kode rekening;
    repeat
        :Memilih salah satu
        kode rekening;
        :Mengalokasikan RAK;
        note left
            Input:
            - Jan s.d. Des
            Metode:
            - Mengisi manual per bulan
            - Bagi per termin
            - Bagi per persentase x termin
            - Bagi rata per bulan
        end note
        if (simpan?) then (yes)
            :simpan data;
            |Aplikasi Siskeudes (System)|
            :Menyimpan
            input RAK;
        else (no)
            |Operator Desa (Administrator)|
            :batal;
            |Aplikasi Siskeudes (System)|
            :clear data input;
        endif
        |Operator Desa (Administrator)|
    repeat while (Data Lain?) is (yes)
    ->no;
    stop
fork again
    :**Pembiayaan**;
    :Men-load/Mengupdate
    anggaran pembiayaan
    per kode rekening;
    repeat
        :Memilih salah satu
        kode rekening;
        :Mengalokasikan RAK;
        note left
            Input:
            - Jan s.d. Des
            Metode:
            - Mengisi manual per bulan
            - Bagi per termin
            - Bagi per persentase x termin
            - Bagi rata per bulan
        end note
        if (simpan?) then (yes)
            :simpan data;
            |Aplikasi Siskeudes (System)|
            :Menyimpan
            input RAK;
        else (no)
            |Operator Desa (Administrator)|
            :batal;
            |Aplikasi Siskeudes (System)|
            :clear data input;
        endif
        |Operator Desa (Administrator)|
    repeat while (Data Lain?) is (yes)
    ->no;
    stop
    @enduml