@startuml
title "Saldo Awal Laporan Kekayaan Desa"
|Operator Desa (Administrator)|
start
:Klik Menu Saldo Awal
pada Data Entri 
PenataUsahaan;

|Aplikasi Siskeudes (System)|
:Menampilkan Menu
Saldo Awal Kekayaan Desa;
note right
    ..........................
end note
|Operator Desa (Administrator)|
repeat
    :Menambahkan Akun
    Saldo Awal;
    note left
        Input:
        - Kode Rekening
        - Nama Rekening
        - Saldo Debet
        - Saldo Kredit
    end note
    if (simpan?) then (yes)
        :simpan data;
        |Aplikasi Siskeudes (System)|
        :Menyimpan input
        Saldo Awal;

    else (no)
        |Operator Desa (Administrator)|
        :batal;
        |Aplikasi Siskeudes (System)|
        :clear data input;
    endif
    |Operator Desa (Administrator)|
repeat while (Data Lain?) is (yes)
->no;
stop
@enduml