@startuml
title "Saldo Awal Laporan Kekayaan Desa"
|Operator Desa (Administrator)|
start
:Klik Menu Saldo Awal
pada Data Entri
PenataUsahaan;

|Aplikasi Siskeudes (System)|
:Menampilkan Menu
Saldo Awal Kekayaan Desa;
note right
    ..........................
end note

|Operator Desa (Administrator)|
:Pilih Desa;
fork
    :**ASET (Debit)**;
    repeat
        :Menambahkan Akun
        Saldo Awal;
        note left
            Input:
            - Kode Rekening
            - Nama Rekening
            (otomatis generated)
            - Nilai (Rp)
        end note
        if (simpan?) then (yes)
            :simpan data;
            |Aplikasi Siskeudes (System)|
            :Menyimpan input
            data aset;

        else (no)
            |Operator Desa (Administrator)|
            :batal;
            |Aplikasi Siskeudes (System)|
            :clear data input;
        endif
        |Operator Desa (Administrator)|
    repeat while (Data Lain?) is (yes)
    ->no;
fork again
    :**KEWAJIBAN (Kredit)**;
    repeat
        :Menambahkan Akun
        Saldo Awal;
        note left
            Input:
            - Kode Rekening
            - Nama Rekening
            (otomatis generated)
            - Nilai (Rp)
        end note
        if (simpan?) then (yes)
            :simpan data;
            |Aplikasi Siskeudes (System)|
            :Menyimpan input
            data aset;

        else (no)
            |Operator Desa (Administrator)|
            :batal;
            |Aplikasi Siskeudes (System)|
            :clear data input;
        endif
        |Operator Desa (Administrator)|
    repeat while (Data Lain?) is (yes)
    ->no;
    endmerge
    :Memilih tombol "Hitung Ekuitas";
    |Aplikasi Siskeudes (System)|
    :Melakukan perhitungan ekuitas;
    |Operator Desa (Administrator)|
    if (simpan?) then (yes)
        |Aplikasi Siskeudes (System)|
        :Menyimpan output
        data ekuitas;
    else (no)
        :clear data input;
    endif
    |Operator Desa (Administrator)|
    stop
    @enduml